// <auto-generated />
namespace UniManagementApp.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CNIC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CNIC));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291041211_CNIC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
